### ISSUE TITLE
Any guide?

### ISSUE THREAD

**Issue by zix3r** [FlynnD273/GarticDrawer#1]
Wanna know how to use this exactly

**Comment by FlynnD273** [comment]
No guide for now. I might try to re-write this to use Playwright so it'll just work on any platform in the future though. 

You should run `gartic_evo.py`, since that one's the best in my opinion. I don't actually know if it'll work for you, I was running this in Firefox on X11 Ubuntu. I'm almost certain the screen coordinates will be different fir you. You can run `python gartic_evo.py` and it'll print out some help for what the different arguments do. The required Python modules should just be `pynput`, `numpy,` and `OpenCV`. 

For now, these two lines store the coordinates for the colour buttons: https://github.com/FlynnD273/GarticDrawer/blob/f49be746702fb7ddf8ef17c7c682435544414cb6/gartic_evo.py#L156

This one is the list of coordinates for the paint brush size options: https://github.com/FlynnD273/GarticDrawer/blob/f49be746702fb7ddf8ef17c7c682435544414cb6/gartic_evo.py#L136

Eraser is hardcoded here: https://github.com/FlynnD273/GarticDrawer/blob/f49be746702fb7ddf8ef17c7c682435544414cb6/gartic_evo.py#L119

Square fill tool is hardcoded here: https://github.com/FlynnD273/GarticDrawer/blob/f49be746702fb7ddf8ef17c7c682435544414cb6/gartic_evo.py#L202

I think it'd be cool to add a calibration step where I have you click on everything. But this was just a tiny side-project to test out different drawing techniques.

**Comment by FlynnD273** [comment]
I've updated the program to use Playwright, and I've added a more fleshed-out README too. Feel free to open a new issue if you've any other questions.
